INSERT INTO books (book_id,book_name,book_price) VALUES (1, 'The Lord of the rings: The Fellowship of the Ring', 1299.00);
INSERT INTO books (book_id,book_name,book_price) VALUES (2, 'The Lord of the rings: The Two Towers', 1099.00);
INSERT INTO books (book_id,book_name,book_price) VALUES (3, 'The Lord of the rings: The Return of the King', 1100.99);
INSERT INTO books (book_id,book_name,book_price) VALUES (4, 'Harry Potter and the Philosophers Stone', 799.00);
INSERT INTO books (book_id,book_name,book_price) VALUES (5, 'Harry Potter and the Chamber of Secrets', 600.00);
INSERT INTO books (book_id,book_name,book_price) VALUES (6, 'Harry Potter and the Prisoner of Azkaban', 899.00);
INSERT INTO books (book_id,book_name,book_price) VALUES (7, 'Harry Potter and the Goblet of Fire', 799.00);
INSERT INTO books (book_id,book_name,book_price) VALUES (8, 'Harry Potter and the Order of the Phoenix', 600.00);
INSERT INTO books (book_id,book_name,book_price) VALUES (9, 'Harry Potter and the Half-Blood Prince', 599.00);
INSERT INTO books (book_id,book_name,book_price) VALUES (10, 'Harry Potter and the Deathly Hallows', 899.00);